### ISSUE TITLE
Issue installing 

### ISSUE THREAD

**Issue by ratpunk2** [ElliotAlderson51/Brute-Force#1]
Collecting validate_email
  Using cached validate_email-1.3.tar.gz (4.7 kB)
Requirement already satisfied: colored in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (1.4.2)
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.6.0)
Collecting pywifi
  Using cached pywifi-1.1.12-py3-none-any.whl (15 kB)
ERROR: Could not find a version that satisfies the requirement zipfile (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for zipfile (from -r requirements.txt (line 5))

**Comment by ElliotAlderson51** [comment]
I deleted the zipfile from the requirements file because the zipfile package installed together with Python.
